### PR TITLE
First attempt on correction

### PR DESCRIPTION
**Pull request by SiewYan**

### CODE REVIEW

**Comment by SiewYan** [comment]
Hi, I have some concern on the part where it shows puppi softdrop mass distribution (page 23), do we need to reproduce the same distribution with PF soft drop mass distribution?
Also, could you take a look at the signal extraction part? thanks

**Comment by SiewYan** [comment]
Below items need discussion before executing (might involve correction on the equation.)
1.) Remove transfer factor from fail to pass 
2.) Remove Pt-depdendent shape uncertainty stem from removal of "from fail to pass TF".

**Comment by mcremone** [comment]
Please revert back the changes you do in the jet session (AK4 and CA15), putting back PUPPI-weighted or PUPPI corrections everywhere. Even though we switched to PFMET we are still using PUPPI jets and PUPPI corrections for them.

**Comment by mcremone** [comment]
Please also remove the following descriptions:

- measurement of n2DDT signal scale factors
- measurement of the double-b signal scale factor
- independent measurement of the double-b mistag scale factor for ttbar

and add a reference to their description in the mono-Hbb note. There is really no need to repeat word by word their description.

**Comment by SiewYan** [comment]
I have done what is requested. Please check this is ok or not. thanks

**Comment by SiewYan** [comment]
Remove Pt-dependent description

**Pull request merged**
